apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-users-postgres
  namespace: plateforme-educative
  labels:
    app: db-users-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-users-postgres
  template:
    metadata:
      labels:
        app: db-users-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: PG_USER_SERVICE_DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: PG_USER_SERVICE_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: PG_USER_SERVICE_PASSWORD
        volumeMounts:
        - name: pgdata-users
          mountPath: /var/lib/postgresql/data
        readinessProbe: # Healthcheck pour savoir quand la BDD est prÃªte
          tcpSocket:
            port: 5432
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          periodSeconds: 20
      volumes:
      - name: pgdata-users
        persistentVolumeClaim:
          claimName: db-users-postgres-pvc